sudo: required

services:
  - docker

env:
  matrix:
    - CI_ROS_DISTRO="melodic"

install:
  - docker build -t mir_experiments:0.6 -f ./containers/Dockerfile .

scripts: 
  - docker-compose -f ./containers/Dockerfile up
  - docker-compose -f ./containers/Dockerfile stop

notifications:
  email: false